import { ApplicationDetails } from '@/Constants/ApplicationDetails';
import React from 'react'
import ForgetPasswordForm from './components/ForgetPasswordForm';


export const metadata = {
  title: `${ApplicationDetails.ApplicationName} | Forget Password | `,
  description: "Generated by create next app",
};

const ForgetPassword = () => {
  return (
    <ForgetPasswordForm />
  )
}

export default ForgetPassword