import { ApplicationDetails } from '@/Constants/ApplicationDetails';
import React from 'react'
import RegisterForm from './components/RegisterForm';

export const metadata = {
    title: `${ApplicationDetails.ApplicationName} | Register | ${ApplicationDetails.ApplicationVersion}`,
    description: "Generated by create next app",
  };

const RegisterPage = () => {
  return (
    <div className='font-bold text-4xl'>
      <RegisterForm />
    </div>
  )
}

export default RegisterPage