import { ApplicationDetails } from '@/Constants/ApplicationDetails';
import React from 'react'
import LoginForm from './components/LoginForm';

export const metadata = {
  title: `${ApplicationDetails.ApplicationName} | Login | ${ApplicationDetails.ApplicationVersion}`,
  description: "Generated by create next app",
};

const Loginpage = () => {
  return (
    <div className='font-bold text-4xl'>
      <LoginForm />
    </div>
  )
}

export default Loginpage
